learning.Northwind.MvcUI/Models/CartListViewModel.cs
using learning.Northwind.Entities.Concrete;

namespace learning.Northwind.MvcUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }
    }
}

learning.Northwind.MvcUI/Models/CategoryListViewModel.cs
using learning.Northwind.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace learning.Northwind.MvcUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; internal set; }
        public int CurrentCategory { get; internal set; }
    }
}

learning.Northwind.MvcUI/Models/ErrorViewModel.cs
using System;

namespace learning.Northwind.MvcUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

learning.Northwind.MvcUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using learning.Northwind.Entities.Concrete;

namespace learning.Northwind.MvcUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; internal set; }
        public int PageCount { get; internal set; }
        public int PageSize { get; internal set; }
        public int CurrentCategory { get; internal set; }
        public int CurrentPage { get; internal set; }
    }
}

learning.Northwind.MvcUI/Models/ShippingDetailsViewModel.cs
using learning.Northwind.Entities.Concrete;

namespace learning.Northwind.MvcUI.Models
{
    public class ShippingDetailsViewModel
    {
        public ShippingDetails ShippingDetails { get; set; }
    }
}

learning.Northwind.MvcUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using learning.Northwind.Bussiness.Abstract;
using learning.Northwind.Entities.Concrete;
using learning.Northwind.MvcUI.Models;
using learning.Northwind.MvcUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace learning.Northwind.MvcUI.Controllers
{
    public class CartController : Controller
    {
        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(ICartSessionService cartSessionService, ICartService cartService, IProductService productService)
        {
            _cartSessionService = cartSessionService;
            _cartService = cartService;
            _productService = productService;
        }

        public ActionResult AddToCart(int productId)
        {
            var productToBeAdded = _productService.GetById(productId);
            var cart = _cartSessionService.GetCart();
            _cartService.AddToCart(cart, productToBeAdded);
            _cartSessionService.SetCart(cart);
            TempData.Add("message", String.Format("Your product, {0}, was successfully added to the cart",productToBeAdded.ProductName));
            return RedirectToAction("Index", "Product");
        }

        public ActionResult List()
        {
            var cart = _cartSessionService.GetCart();
            CartListViewModel cartListViewModel = new CartListViewModel
            {
                Cart = cart
            };
            return View(cartListViewModel);
        }


        public ActionResult Remove(int productId)
        {
            var cart = _cartSessionService.GetCart();
            _cartService.RemoveFromCart(cart,productId);
            _cartSessionService.SetCart(cart);
            TempData.Add("message", String.Format("Your product was successfully removed from the cart"));
            return RedirectToAction("List");

        }

        public ActionResult Complete()
        {
            var shippingDetailsViewModel = new ShippingDetailsViewModel
            {
                ShippingDetails=new ShippingDetails()
            };
            return View(shippingDetailsViewModel);
        }

        [HttpPost]
        public ActionResult Complete(ShippingDetails shippingDetails)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message",String.Format("Thank you {0}, your order is submitted.",shippingDetails.FirstName));
            return View();
        }

    }


}

learning.Northwind.MvcUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using learning.Northwind.MvcUI.Models;

namespace learning.Northwind.MvcUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

learning.Northwind.MvcUI/Controllers/ProductController.cs
using learning.Northwind.Bussiness.Abstract;
using learning.Northwind.MvcUI.Models; 
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace learning.Northwind.MvcUI.Controllers
{
    public class ProductController:Controller
    {
        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public ActionResult Index(int page=1, int category=0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategoryId(category);
            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Skip((page - 1)*pageSize).Take(pageSize).ToList(),
                PageCount=(int)Math.Ceiling(products.Count/(double)pageSize),
                PageSize=pageSize,
                CurrentCategory=category,
                CurrentPage=page

            };
            return View(model);
        }

     
    }
}

learning.Northwind.MvcUI/ViewComponents/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using learning.Northwind.Bussiness.Abstract;
using learning.Northwind.MvcUI.Models;
using learning.Northwind.MvcUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace learning.Northwind.MvcUI.ViewComponents
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private ICartSessionService _cartSessionService;

        public CartSummaryViewComponent(ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CartListViewModel
            {
                Cart = _cartSessionService.GetCart()
            };
            return View(model);
        }
    }
}

learning.Northwind.MvcUI/ViewComponents/CategoryListViewComponent.cs
using learning.Northwind.Bussiness.Abstract;
using learning.Northwind.MvcUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace learning.Northwind.MvcUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory=Convert.ToInt32(HttpContext.Request.Query["category"])

            };
            return View(model);
        }

    }
}

learning.Northwind.MvcUI/Views/Cart/Complete.cshtml
@model ShippingDetailsViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Shipping Details</h2>
<form asp-controller="Cart" asp-action="Complete" method="post">
    <div class="form-group">
        <label asp-for="ShippingDetails.FirstName"></label>
        <input asp-for="ShippingDetails.FirstName" class="form-control" placeholder="First Name">
        <span asp-validation-for="ShippingDetails.FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.LastName"></label>
        <input asp-for="ShippingDetails.LastName" class="form-control" placeholder="Last Name">
        <span asp-validation-for="ShippingDetails.LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.Address"></label>
        <input asp-for="ShippingDetails.Address" class="form-control" placeholder="Address">
        <span asp-validation-for="ShippingDetails.Address"></span>
    </div>
    <div class="form-group">
        <label asp-for="ShippingDetails.City"></label>
        <input asp-for="ShippingDetails.City" class="form-control" placeholder="City">
        <span asp-validation-for="ShippingDetails.City"></span>
    </div>

    <div class="form-group">
        <label asp-for="ShippingDetails.Email"></label>
        <input asp-for="ShippingDetails.Email" class="form-control" placeholder="Email">
        <span asp-validation-for="ShippingDetails.Email"></span>
    </div>

    
    <input type="submit" value="Complete Shopping" class="btn btn-xs btn-success" />
</form>

learning.Northwind.MvcUI/Views/Cart/List.cshtml
@model learning.Northwind.MvcUI.Models.CartListViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Cart</h2>
<table class="table">
    <tr>
        <td>Product Name</td>
        <td>Unit Price</td>
        <td>Units In Stock</td>
        <td>Quantity</td>
        <td></td>
    </tr>
    @foreach (var item in Model.Cart.CartLines)
    {
        <tr>
            <td>@item.Product.ProductName</td>
            <td>@item.Product.UnitPrice</td>
            <td>@item.Product.UnitsInStock</td>
            <td>@item.Quantity</td>
            <td class="text-right"><a class="btn btn-xs btn-danger" asp-controller="Cart" asp-action="Remove" asp-route-productId="@item.Product.ProductId"><span class="glyphicon glyphicon-remove"></span> remove from cart</a></td>
        </tr>
    }
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>
            <h3>Total</h3>
        </td>
        <td class="text-right">
            <h3>
                <strong>@Model.Cart.Total</strong>
            </h3>
        </td>
    </tr>
    <tr>
        <td> </td>
        <td> </td>
        <td> </td>
        <td>
            <a asp-controller="Product" asp-action="Index" class="btn btn-xs btn-default">
                <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
            </a>
        </td>
        <td class="text-right">
            <a asp-controller="Cart" asp-action="Complete" class="btn btn-xs btn-success">
                <span class="glyphicon glyphicon-shopping-play"></span> Go To Checkout
            </a>
        </td>
    </tr>
</table>

learning.Northwind.MvcUI/Views/Product/index.cshtml
@model ProductListViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <table class="table table-responsive">
        <tr>
            <td>Product Name</td>
            <td>Unit Price</td>
            <td>Units in Stock</td>
            <td></td>
        </tr>
        @foreach (var product in Model.Products)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
                <td><a class="btn btn-xs btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.ProductId">Add to cart</a></td>
            </tr>
        }

    </table>
</div>
<product-list-pager current-page="@Model.CurrentPage"
                    current-category="@Model.CurrentCategory"
                    page-count="@Model.PageCount"
                    page-size="@Model.PageSize"></product-list-pager>

learning.Northwind.MvcUI/Views/Shared/Components/CartSummary/Default.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Conventions
@model learning.Northwind.MvcUI.Models.CartListViewModel

<ul class="dropdown-menu" style="padding: 10px" aria-labelledby="navbarDropdown">
    @foreach (var item in Model.Cart.CartLines)
    {
    <li>@item.Product.ProductName <span class="badge">@item.Quantity</span></li>
    }
    <li role="seperator" class="dropdown-divider"></li>
    <li><a>@Model.Cart.Total</a></li>
    <li role="seperator" class="dropdown-divider"></li>
    <li><a asp-controller="Cart" asp-action="List">Go to Cart Details</a></li>
</ul>

learning.Northwind.MvcUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<div class="list-group">

    @foreach(var category in Model.Categories)
    {
        var css = "list-group-item";
        if(category.CategoryId==Model.CurrentCategory)
        {
            css += " active";
        }
        <a href="/product/index?category=@category.CategoryId" class="@css">@category.CategoryName</a>
    }
</div>

learning.Northwind.MvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="/node_modules/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>



</head>
<body>
    <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Stock Check</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
                <div class="nav-item dropdown navbar-right">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    @await Component.InvokeAsync("CartSummary")
                </div>
            </div>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-2">
        @await Component.InvokeAsync("CategoryList")
        </div>
    <div class="col-md-10">
        @if (TempData["message"]!=null)
        {
            <div class="alert alert-info" role="alert">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    </div>
    
    <div class="col-md-12">Footer</div>
</body>
</html>